[settings]
clients=female-client,male-client

[discord]
token=YOUR DISCORD BOT TOKEN
; Guild Id for a bot
guild-id=1270812703874879663
; Log channel id where bot want send mesasges
channel-id=1419213946967031869
; Default: False
reconnect=True
; 5 seconds
reconnect-delay=15 
; Start command
start-command=$s
; Stop command
stop-command=$st

[client/female-client]
user_id=YOUR USER ID
ua=YOUR USER AGENT
sex=MALE
search-sex=FEMALE
age=0,17
search-age=0,17

[client/male-client]
user_id=YOUR USER ID
ua=YOUR USER AGENT
sex=FEMALE
search-sex=MALE
age=0,17
search-age=0,17
